### ISSUE TITLE
Sharp corners problems at the ice-land-open water in compression

### ISSUE THREAD

**Issue by dringeis** [dringeis/MITgcm#2]
There are allegedly weird velocity solutions in the VP sea ice model at the corner of an interface ice-land-open water in uni-axial compression; James Williams, personal communication.

### Tasks:
- [x] Plot the problem with the elliptical yield curve (velocity, deformation, and residual).
  - [x] Velocity
  - [x] Deformation
  - [x] Residual 
  - [x] Plot the ArkawaC grid velocity
- [ ] Explain the inversed velocities
  - [x] Test in a free drift set-up if the velocity inversion also happens
  - [x] Test with more LSR iterations if the problem persists (numerical convergence problem 
- [ ] Ideas for after:
 - [ ] Test if a smooth ice-open water border would solve the alleged problem.
 - [ ] Test if the smooth border solution changes the failure angles.
 - [ ] Implement the smooth ice-open water in the other rheological uniaxial compression experiments if it works.
 - [ ] If it does not work, try a free drift shore condition.

**Comment by dringeis** [comment]
### Velocity at the corner: 

![Screenshot from 2022-07-25 18-27-49](https://user-images.githubusercontent.com/30409025/180884654-fa5c531e-ac23-4ce3-9b18-3ef738503243.png)

The fact that the velocity goes inward at the border is kinda weird.

### Shear at the corner:

![Screenshot from 2022-07-25 18-29-33](https://user-images.githubusercontent.com/30409025/180884980-036b0ae2-721f-43a3-8c9a-b5445e754fd8.png)

Nothing too weird here

### Numerical residual

The LSR residual diagnostic does not work at the moment, problem in the INM branch

### Parameters
- Folder: /storage/dringeisen/MITgcm_runs/MITgcm_CornerTest/run00
- Branch: master (same as upstream/master) 
- Default parameters from MITgcm except:
  - Replacement pressure off
  - kt = 0.05

**Comment by dringeis** [comment]
The bug in the INM branch is fixed.

### The residual 
![Screenshot from 2022-07-26 11-44-12](https://user-images.githubusercontent.com/30409025/181050731-532e0028-e7c4-4094-8df9-1c3d38f689ee.png)
Nothing special appears here.

###

I do not a big problem with numerical convergence here. 

One thing not to forget is that U and V and H/A are not at the same place on the grid. The quiver representation is then not very accurate. To change.

**Comment by dringeis** [comment]
## New velocity plot

We now plot the velocities UV at the correct place in the ArakawaC grid

![Screenshot from 2022-07-28 10-54-01](https://user-images.githubusercontent.com/30409025/181568827-1a0ecfd8-6370-4ccb-b2eb-e41a72a8b15d.png)

We see that the velocity in U is small but can be inverted.

Here is the velocity in time. It becomes negative suddenly, then decreases slowly to zero. 
![Screenshot from 2022-07-28 11-12-49](https://user-images.githubusercontent.com/30409025/181574046-fabee6bb-a17e-4de3-bd63-1d999268f190.png)

The velocity becomes negative as the stress SIsigI suddenly jumps from 0 to almost -1.

![Screenshot from 2022-07-28 11-16-41](https://user-images.githubusercontent.com/30409025/181575004-34bfd4b0-ae46-4c57-885f-2f7ee8bbbcd1.png) 


Still no problem in the residuals (checked but not shown)

**Comment by dringeis** [comment]
- The velocity inversion does not appear in the free drift setup. (folder run01)
 - The velocity inversion does appear in the more converged setup (folder run02)
![Screenshot from 2022-07-28 16-45-05](https://user-images.githubusercontent.com/30409025/181634299-9a930d32-4a64-4901-8584-be271ea7357e.png)

   - But it is not the main problem here: The velocities are much much higher (2 orders of mag) in run02 than in run00. The fracture is also nicer, more precise and defined.

![Screenshot from 2022-07-28 16-36-50](https://user-images.githubusercontent.com/30409025/181632778-cda896b2-1885-40ec-9817-4c772ada1a03.png)

With the residuals:

![Screenshot from 2022-07-28 16-40-34](https://user-images.githubusercontent.com/30409025/181633470-a0fafd4d-c990-43fe-ba51-526883bfd2ac.png)

**Comment by dringeis** [comment]
There is often an episode of inversed velocities in the cells newly covered by sea ice
![Screenshot from 2022-07-28 16-48-32](https://user-images.githubusercontent.com/30409025/181635386-03756b66-424a-4f6e-8454-a603997a16f2.png)
, often when the stress goes suddenly from 0 to ca. -1. 
![Screenshot from 2022-07-28 16-51-59](https://user-images.githubusercontent.com/30409025/181635418-cd26ff14-8b12-4a16-a31e-c3cf1a31fe6d.png)
